// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4wqKjMoAH0naOXHgU75h_51npddmYR6M',
    appId: '1:822107823206:web:075f911e028cd1d81421a7',
    messagingSenderId: '822107823206',
    projectId: 'blind-date-jg',
    authDomain: 'blind-date-jg.firebaseapp.com',
    storageBucket: 'blind-date-jg.firebasestorage.app',
    measurementId: 'G-12Z8PB5PN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTD7TGPtykKTlMfz5XD0F8creyWryuiNE',
    appId: '1:822107823206:android:33218f167bf55a001421a7',
    messagingSenderId: '822107823206',
    projectId: 'blind-date-jg',
    storageBucket: 'blind-date-jg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq-I1OGJpWJ2ENgWuPVfwoag2A0RD4078',
    appId: '1:822107823206:ios:ab16aaa604f3b07c1421a7',
    messagingSenderId: '822107823206',
    projectId: 'blind-date-jg',
    storageBucket: 'blind-date-jg.firebasestorage.app',
    iosBundleId: 'com.example.meeting',
  );
}
